[package]
name = "rw_lease"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[features]
async = ["event-listener", "simple-mutex"]
default = ["async"]

[dependencies]
atomic_prim_traits = "0.1"
primitive_traits = "0.2"

[dependencies.event-listener]
version = "2.2"
optional = true

[dependencies.simple-mutex]
version = "1.1"
optional = true

